version: '3'

services:
  traefik:
    image: traefik:v2.9
    hostname: traefik
    ports:
      - target: 443
        published: 444
        mode: host
      - target: 80
        published: 81
        mode: host
      - target: 6379
        published: 6379
        mode: host
      - target: 5432
        published: 5432
        mode: host
      - target: 8080
        published: 8081
        mode: host
    networks:
      - attachable
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 30
        window: 30s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/docker/stag/reverse-proxy-traefik/traefik.yml:/etc/traefik/traefik.yml

networks:
  attachable:
    name: bigsizeship-net
    driver: overlay
    attachable: true
