version: "3"

services:
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - 6379
    command: redis-server --appendonly yes --replica-read-only no --bind 0.0.0.0
    networks:
      - redis-net
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.tcp.routers.redis.rule=HostSNI(`*`)
        - traefik.tcp.routers.redis.entrypoints=redis
        - traefik.docker.network=bigsizeship-net
        - traefik.tcp.routers.redis.service=redis
        - traefik.tcp.services.redis.loadbalancer.server.port=6379

    volumes:
      - cache:/data

networks:
  redis-net:
    external: true
    name: bigsizeship-net

volumes:
  cache:
    driver: local
