# https://blog.jannikwempe.com/github-actions-trunk-based-development#heading-a-brief-introduction-to-trunk-based-development
name: Build & push docker image

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Optional input to set an operating systems which the workflow uses."
        required: false
        type: string
        default: "ubuntu-latest"
      docker-context:
        description: "Optional input to set docker context."
        required: false
        type: string
        default: "."
      docker-platforms:
        description: "Optional input list to set docker target platforms for build."
        required: false
        type: string
        default: "linux/amd64"
      git-ref:
        description: "Optional input to set git branch, tag or SHA to checkout."
        required: false
        type: string
        default: ""
      publish_to_github_cr:
        type: boolean
        description: "Whether to publish the image to Github Container Registry."
        required: false
        default: false


jobs:
  docker-build-push:
    name: Build & push docker image
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          ref: ${{ inputs.git-ref}}
          fetch-depth: ${{inputs.git-ref}} && 0 || 1 # In git-ref case: fetch all history for all branches and tags

      - name: Build, tag & push docker image
        uses: BigsizeShip/infrastructure/.github/actions/docker-build-tag-push
        with:
          docker-context: ${{inputs.docker-context}}
          docker-platforms: ${{inputs.docker-platforms}}
          publish_to_github_cr: ${{inputs.publish_to_github_cr}}