# https://stackoverflow.com/questions/76555305/postgres-container-failed-to-start-with-initdb-error-popen-failure-cannot-allo
# https://forums.docker.com/t/docker-swarm-networking-hostnames-and-service-names/90489/6
version: "3"

services:
  postgres:
    image: postgres:15.4-bullseye
    hostname: postgres
    command: postgres -c listen_addresses='*'
    environment:
      POSTGRES_USER: strapi_admin
      POSTGRES_PASSWORD: bigsizeship@123
      POSTGRES_DB: bigsizeship_db
    ports:
      - 5432
    networks:
      - postgres-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.tcp.routers.postgres.rule=HostSNI(`*`)
        - traefik.tcp.routers.postgres.entrypoints=postgres
        - traefik.docker.network=bigsizeship-net
        - traefik.tcp.routers.postgres.service=postgres
        - traefik.tcp.services.postgres.loadbalancer.server.port=5432

networks:
  postgres-net:
    external: true
    name: bigsizeship-net


volumes:
  pgdata:
    driver: local