name: Build and Deploy BigsizeShip-Backend

on:
  workflow_dispatch:
    inputs: 
      project-name:
        description: 'PROJECT NAME (Ex: bigsizeship-backend)'    
        required: false
        default: "bigsizeship-backend"
      env:
        type: choice
        description: '[Mandatory] SELECT environment'
        options:
        - stag
        - prod
      git-tag:
        description: '[Mandatory] GIT TAG (Ex: 1.0.0.1)'
        required: false
      commit-id:
        description: '[Optional] Commit ID'
        required: false     
      commit-author:
        description: '[Optional] AUTHOR'    
        required: false   
      image-tag:
        description: '[Mandatory] DOCKER TAG (Ex: 1.0.0.1)'    
        required: false
      docker-context:
        description: "Optional input to set docker context"
        required: false
        type: string
        default: "."

jobs:
#=============== CI/CD stag environment ===============#
  bigsizeship-backend-STAG-build:
    name: bigsizeship-backend STAG build
    if: ${{ github.event.inputs.env == 'stag' }}
    runs-on: ubuntu-latest
    outputs:
      job_status: ${{ job.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build, tag & push docker image
        uses: ./.github/actions/${{ github.event.inputs.project-name }}@master
        with:
          env: ${{ github.event.inputs.env }}


  bigsizeship-backend-STAG-deploy:
    name: bigsizeship-backend STAG deploy
    needs: bigsizeship-backend-STAG-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/${{ github.event.inputs.project-name }}@master
        with:
          env: ${{ github.event.inputs.env }}
          tag: ${{ github.event.inputs.image-tag }}
          stack_name: bigsizeship_be_staging

      # Clean Workspace
      - name: Clean Workspace
        uses: AutoModality/action-clean@v1
