name: Build and Deploy BigsizeShip-Backend

on:
  workflow_dispatch:
    inputs: 
      PROJECT_NAME:
        description: 'PROJECT NAME (Ex: bigsizeship-backend)'    
        required: false
        default: "bigsizeship-backend"
      ENV:
        type: choice
        description: '[Mandatory] SELECT ENVIRONMENT'
        options:
        - stag
        - prod
      GIT_TAG:
        description: '[Mandatory] GIT TAG (Ex: 1.0.0.1)'
        required: false
        default: master
      COMMIT_ID:
        description: '[Optional] Commit ID'
        required: false     
      COMMIT_AUTHOR:
        description: '[Optional] AUTHOR'    
        required: false   
      IMAGE_TAG:
        description: '[Mandatory] DOCKER TAG (Ex: 1.0.0.1)'    
        required: false

jobs:
#=============== CI/CD stag environment ===============#
  bigsizeship-backend-STAG-build:
    name: bigsizeship-backend STAG build
    if: ${{ inputs.ENV == 'stag' }}
    runs-on: ubuntu-latest
    outputs:
      job_status: ${{ job.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build, tag & push docker image
        uses: ./.github/actions/bigsizeship-backend/build
        with:
          ENV: ${{ inputs.ENV }}
          PROJECT_NAME: ${{ inputs.PROJECT_NAME }}
          GIT_TAG: ${{ inputs.GIT_TAG }}


  bigsizeship-backend-STAG-deploy:
    name: bigsizeship-backend STAG deploy
    needs: bigsizeship-backend-STAG-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/bigsizeship-backend/deploy
        with:
          env: ${{ inputs.ENV }}
          tag: ${{ inputs.IMAGE_TAG }}
          stack_name: bigsizeship_be_staging

      # Clean Workspace
      - name: Clean Workspace
        uses: AutoModality/action-clean@v1
