version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    hostname: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx512m -Xms512m
      ELASTIC_USERNAME: bigsizeship
      ELASTIC_PASSWORD: bigsizeship@123
      xpack.security.enabled: "false"
      network.host: 0.0.0.0
      node.name: es01
      cluster.name: elasticsearch
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200
    networks:
      - elastic-net

networks:
  elastic-net:
    external: true
    name: bigsizeship-net

volumes:
  esdata:
    driver: local
